project:
  type: book
  output-dir: _book
  resources:
    - docs/**
    - images/**

book:
  title: "Modelos probabilísticos en Biología Evolutiva: diversificación, morfología, biogeografía y tendencias"
  author: "Karen López, Ixchel González y Cristian Cervantes"
  date: today
  page-navigation: true
  search: true
  sidebar:
    logo: images/Logo_UNISSE_blanco.png
    title: "Modelos probabilísticos en Biología Evolutiva: diversificación, morfología, biogeografía y tendencias"
    collapse-level: 1
    pinned: true
  repo-url: https://github.com/IB-UNISSE/patrones_filogeneticos
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - chapters/install.qmd
    - chapters/commandline.qmd
    - chapters/Rstudio.qmd
    - chapters/revbayes.qmd
    - chapters/docker.qmd
    - chapters/factor_bayes.qmd
    - part: "Unidad 1: Patrones de diversificación"
      chapters:
        - chapters/u1_intro_diversification.qmd
        - chapters/u1_intro_diversification_2.qmd
        - chapters/u1_intro_diversification_3.qmd
        - chapters/u1_intro_diversification_4.qmd
    - part: "Unidad 2: Patrones biogeográficos"
      chapters:
        - chapters/u2_intro_biogeography_1.qmd
        - chapters/u2_intro_biogeography_2.qmd
        - chapters/u2_intro_biogeography_3.qmd
    - part: "Unidad 3: Patrones morfológicos"
      chapters:
        - chapters/u3_intro_morphology_1.qmd
        - chapters/u3_intro_morphology_2.qmd

format:
  html:
    theme:
      light: litera
    css: styles/styles.css
    toc: true
    toc-depth: 3
    number-sections: false
    code-copy: true
    code-overflow: wrap
    smooth-scroll: true
    link-external-newwindow: true

website:
  site-url: https://ib-unisse.github.io/patrones_filogeneticos/

editor: visual

publish:
  gh-pages:
    branch: gh-pages
    dir: _book

